Update error.yaml

diff --git a/.github/workflows/error.yaml b/.github/workflows/error.yaml
--- a/.github/workflows/error.yaml
+++ b/.github/workflows/error.yaml
@@ -13,4 +13,4 @@ jobs:
           ref: "main"
       - name: Test application
         run: |
-          echo "::error title={benchmark-result}::warning"
+          echo "::error title={benchmark-result}::warning" && exit 1
