Update error.yaml

diff --git a/.github/workflows/error.yaml b/.github/workflows/error.yaml
--- a/.github/workflows/error.yaml
+++ b/.github/workflows/error.yaml
@@ -13,5 +13,4 @@ jobs:
           ref: "main"
       - name: Test application
         run: |
-          echo "Error PR"
-          exit 1 # exit with error status code
+          echo "Error PR" >&2 && exit 1
